USE world;
DROP TABLE IF EXISTS CurrencyCountry;
DROP TABLE IF EXISTS Currency;
CREATE TABLE Currency (
    CurrencyCode CHAR(3) PRIMARY KEY,
    CurrencyName VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

START TRANSACTION;
-- Insert data into Currency table
INSERT INTO Currency (CurrencyCode, CurrencyName) VALUES
('AFN', 'Afghan Afghani'),
('ALL', 'Albanian Lek'),
('DZD', 'Algerian Dinar'),
('USD', 'US Dollar'),
('EUR', 'Euro'),
('AOA', 'Angolan Kwanza'),
('XCD', 'East Caribbean Dollar'),
('ARS', 'Argentine Peso'),
('AMD', 'Armenian Dram'),
('AWG', 'Aruban Florin'),
('AUD', 'Australian Dollar'),
('AZN', 'Azerbaijani Manat'),
('BSD', 'Bahamian Dollar'),
('BHD', 'Bahraini Dinar'),
('BDT', 'Bangladeshi Taka'),
('BBD', 'Barbadian Dollar'),
('BYN', 'Belarusian Ruble'),
('BZD', 'Belize Dollar'),
('XOF', 'West African CFA Franc'),
('BTN', 'Bhutanese Ngultrum'),
('BOB', 'Bolivian Boliviano'),
('BAM', 'Bosnia and Herzegovina Convertible Mark'),
('BWP', 'Botswana Pula'),
('BRL', 'Brazilian Real'),
('BND', 'Brunei Dollar'),
('BGN', 'Bulgarian Lev'),
('BIF', 'Burundian Franc'),
('CVE', 'Cape Verdean Escudo'),
('KHR', 'Cambodian Riel'),
('XAF', 'Central African CFA Franc'),
('CAD', 'Canadian Dollar'),
('CLP', 'Chilean Peso'),
('CNY', 'Chinese Yuan'),
('COP', 'Colombian Peso'),
('KMF', 'Comorian Franc'),
('CRC', 'Costa Rican Colón'),
('CUP', 'Cuban Peso'),
('CUC', 'Cuban Convertible Peso'),
('CZK', 'Czech Koruna'),
('DKK', 'Danish Krone'),
('DJF', 'Djiboutian Franc'),
('DOP', 'Dominican Peso'),
('EGP', 'Egyptian Pound'),
('ERN', 'Eritrean Nakfa'),
('SZL', 'Swazi Lilangeni'),
('ETB', 'Ethiopian Birr'),
('FJD', 'Fijian Dollar'),
('GEL', 'Georgian Lari'),
('GHS', 'Ghanaian Cedi'),
('GTQ', 'Guatemalan Quetzal'),
('GNF', 'Guinean Franc'),
('GYD', 'Guyanese Dollar'),
('HTG', 'Haitian Gourde'),
('HNL', 'Honduran Lempira'),
('HKD', 'Hong Kong Dollar'),
('HUF', 'Hungarian Forint'),
('ISK', 'Icelandic Krona'),
('INR', 'Indian Rupee'),
('IDR', 'Indonesian Rupiah'),
('IRR', 'Iranian Rial'),
('IQD', 'Iraqi Dinar'),
('ILS', 'Israeli New Shekel'),
('JPY', 'Japanese Yen'),
('JOD', 'Jordanian Dinar'),
('KZT', 'Kazakhstani Tenge'),
('KES', 'Kenyan Shilling'),
('KPW', 'North Korean Won'),
('KRW', 'South Korean Won'),
('KWD', 'Kuwaiti Dinar'),
('KGS', 'Kyrgyzstani Som'),
('LAK', 'Lao Kip'),
('LBP', 'Lebanese Pound'),
('LSL', 'Lesotho Loti'),
('LRD', 'Liberian Dollar'),
('LYD', 'Libyan Dinar'),
('CHF', 'Swiss Franc'),
('MOP', 'Macanese Pataca'),
('MGA', 'Malagasy Ariary'),
('MWK', 'Malawian Kwacha'),
('MYR', 'Malaysian Ringgit'),
('MVR', 'Maldivian Rufiyaa'),
('MRU', 'Mauritanian Ouguiya'),
('MUR', 'Mauritian Rupee'),
('MXN', 'Mexican Peso'),
('MDL', 'Moldovan Leu'),
('MNT', 'Mongolian Tögrög'),
('MAD', 'Moroccan Dirham'),
('MZN', 'Mozambican Metical'),
('MMK', 'Myanmar Kyat'),
('NAD', 'Namibian Dollar'),
('NPR', 'Nepalese Rupee'),
('ANG', 'Netherlands Antillean Guilder'),
('NZD', 'New Zealand Dollar'),
('NIO', 'Nicaraguan Córdoba'),
('NGN', 'Nigerian Naira'),
('NOK', 'Norwegian Krone'),
('OMR', 'Omani Rial'),
('PKR', 'Pakistani Rupee'),
('PAB', 'Panamanian Balboa'),
('PGK', 'Papua New Guinean Kina'),
('PYG', 'Paraguayan Guarani'),
('PEN', 'Peruvian Sol'),
('PHP', 'Philippine Peso'),
('PLN', 'Polish Zloty'),
('QAR', 'Qatari Riyal'),
('RON', 'Romanian Leu'),
('RUB', 'Russian Ruble'),
('RWF', 'Rwandan Franc'),
('SAR', 'Saudi Riyal'),
('RSD', 'Serbian Dinar'),
('SCR', 'Seychellois Rupee'),
('SGD', 'Singapore Dollar'),
('SYP', 'Syrian Pound'),
('TWD', 'New Taiwan Dollar'),
('TJS', 'Tajikistani Somoni'),
('TZS', 'Tanzanian Shilling'),
('THB', 'Thai Baht'),
('TMT', 'Turkmenistani Manat'),
('UGX', 'Ugandan Shilling'),
('UAH', 'Ukrainian Hryvnia'),
('AED', 'United Arab Emirates Dirham'),
('GBP', 'British Pound'),
('UYU', 'Uruguayan Peso'),
('UZS', 'Uzbekistani Som'),
('VUV', 'Vanuatu Vatu'),
('VES', 'Venezuelan Bolívar'),
('VND', 'Vietnamese Đồng'),
('XPF', 'CFP Franc'),
('ZMW', 'Zambian Kwacha'),
('ZWL', 'Zimbabwean Dollar');
COMMIT;

DROP TABLE IF EXISTS CurrencyCountry;
CREATE TABLE CurrencyCountry (
    CurrencyCode CHAR(3) NOT NULL,
    CountryCode CHAR(3) NOT NULL,
    PRIMARY KEY (CountryCode, CurrencyCode),
    FOREIGN KEY (CurrencyCode) REFERENCES Currency(CurrencyCode) ON DELETE CASCADE,
    FOREIGN KEY (CountryCode) REFERENCES Country(Code) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

START TRANSACTION;
-- Insert data into CurrencyCountry table
INSERT INTO CurrencyCountry (CurrencyCode, CountryCode) VALUES
('USD', 'USA'),
('USD', 'ECU'),
('USD', 'SLV'),
('USD', 'TMP'),
('USD', 'PLW'),
('USD', 'MHL'),
('AFN', 'AFG'),
('ALL', 'ALB'),
('DZD', 'DZA'),
('USD', 'ASM'),
('EUR', 'AND'),
('AOA', 'AGO'),
('XCD', 'AIA'),
('ARS', 'ARG'),
('AMD', 'ARM'),
('AWG', 'ABW'),
('AUD', 'AUS'),
('EUR', 'AUT'),
('AZN', 'AZE'),
('BSD', 'BHS'),
('BHD', 'BHR'),
('BDT', 'BGD'),
('BBD', 'BRB'),
('BYN', 'BLR'),
('BZD', 'BLZ'),
('XOF', 'BEN'),
('BTN', 'BTN'),
('INR', 'BTN'), -- Bhutan also uses INR
('BOB', 'BOL'),
('BAM', 'BIH'),
('BWP', 'BWA'),
('BRL', 'BRA'),
('BND', 'BRN'),
('BGN', 'BGR'),
('BIF', 'BDI'),
('CVE', 'CPV'),
('KHR', 'KHM'),
('XAF', 'CMR'),
('CAD', 'CAN'),
('CLP', 'CHL'),
('CNY', 'CHN'),
('COP', 'COL'),
('KMF', 'COM'),
('XAF', 'COG'),
('CRC', 'CRI'),
('CUP', 'CUB'),
('CUC', 'CUB'), -- Dual currency
('CZK', 'CZE'),
('DKK', 'DNK'),
('DJF', 'DJI'),
('DOP', 'DOM'),
('EGP', 'EGY'),
('ERN', 'ERI'),
('SZL', 'SWZ'),
-- ('ZAR', 'SWZ'), -- Dual currency
('ETB', 'ETH'),
('FJD', 'FJI'),
('GEL', 'GEO'),
('GHS', 'GHA'),
('GTQ', 'GTM'),
('GNF', 'GIN'),
('GYD', 'GUY'),
('HTG', 'HTI'),
('HNL', 'HND'),
('HKD', 'HKG'),
('HUF', 'HUN'),
('ISK', 'ISL'),
('INR', 'IND'),
('IDR', 'IDN'),
('IRR', 'IRN'),
('IQD', 'IRQ'),
('ILS', 'ISR'),
('JPY', 'JPN'),
('JOD', 'JOR'),
('KZT', 'KAZ'),
('KES', 'KEN'),
('KPW', 'PRK'),
('KRW', 'KOR'),
('KWD', 'KWT'),
('KGS', 'KGZ'),
('LAK', 'LAO'),
('LBP', 'LBN'),
('LSL', 'LSO'),
-- ('ZAR', 'LSO'), -- Dual currency
('LRD', 'LBR'),
('LYD', 'LBY'),
('CHF', 'LIE'),
('EUR', 'LUX'),
('MAD', 'MAR'),
('MGA', 'MDG'),
('MWK', 'MWI'),
('MYR', 'MYS'),
('USD', 'FSM'),
('EUR', 'MLT');
COMMIT;

